apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding
  labels:
    app: onboarding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onboarding
  template:
    metadata:
      labels:
        app: onboarding
    spec:
      containers:
      - image: michaeltengganus/onboarding:latest
        name: onboarding
        ports:
        - containerPort: 3001
        env:
        - name: IS_DOCKER
          value: 'true'
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: onboarding-config
              key: PORT
        - name: DB_DIALECT
          valueFrom:
            configMapKeyRef:
              name: onboarding-config
              key: DB_DIALECT
        - name: DB
          valueFrom:
            configMapKeyRef:
              name: onboarding-config
              key: DB
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: onboarding-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: onboarding-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: onboarding-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: onboarding-secret
              key: DB_PASSWORD
        - name: APP_SETTINGS_FILE_PATH
          valueFrom:
            configMapKeyRef:
              name: onboarding-config
              key: APP_SETTINGS_FILE_PATH
        - name: APM_URL
          valueFrom:
            configMapKeyRef:
              name: onboarding-config
              key: APM_URL
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: onboarding-config
              key: KAFKA_HOST
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: onboarding-secret
              key: SECRET
        - name: EXPIRE_TOKEN
          valueFrom:
            configMapKeyRef:
              name: onboarding-config
              key: EXPIRE_TOKEN
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: onboarding-config
              key: REDIS_PORT
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: onboarding-config
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: onboarding-secret
              key: REDIS_PASSWORD