apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"name":"onboarding"},"name":"onboarding","namespace":"mike"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"onboarding"}},"template":{"metadata":{"labels":{"name":"onboarding"}},"spec":{"containers":[{"env":[{"name":"IS_DOCKER","value":"true"},{"name":"PORT","valueFrom":{"secretKeyRef":{"key":"PORT","name":"onboarding-config"}}},{"name":"DB_DIALECT","valueFrom":{"secretKeyRef":{"key":"DB_DIALECT","name":"onboarding-config"}}},{"name":"DB","valueFrom":{"secretKeyRef":{"key":"DB","name":"onboarding-config"}}},{"name":"DB_HOST","valueFrom":{"secretKeyRef":{"key":"DB_HOST","name":"onboarding-config"}}},{"name":"DB_PORT","valueFrom":{"secretKeyRef":{"key":"DB_PORT","name":"onboarding-config"}}},{"name":"DB_USERNAME","valueFrom":{"secretKeyRef":{"key":"DB_USERNAME","name":"onboarding-config"}}},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"DB_PASSWORD","name":"onboarding-config"}}},{"name":"APP_SETTINGS_FILE_PATH","valueFrom":{"secretKeyRef":{"key":"APP_SETTINGS_FILE_PATH","name":"onboarding-config"}}},{"name":"APM_URL","valueFrom":{"secretKeyRef":{"key":"APM_URL","name":"onboarding-config"}}},{"name":"KAFKA_HOST","valueFrom":{"secretKeyRef":{"key":"KAFKA_HOST","name":"onboarding-config"}}},{"name":"SECRET","valueFrom":{"secretKeyRef":{"key":"SECRET","name":"onboarding-config"}}},{"name":"EXPIRE_TOKEN","valueFrom":{"secretKeyRef":{"key":"EXPIRE_TOKEN","name":"onboarding-config"}}},{"name":"REDIS_PORT","valueFrom":{"secretKeyRef":{"key":"REDIS_PORT","name":"onboarding-config"}}},{"name":"REDIS_HOST","valueFrom":{"secretKeyRef":{"key":"REDIS_HOST","name":"onboarding-config"}}},{"name":"REDIS_PASSWORD","valueFrom":{"secretKeyRef":{"key":"REDIS_PASSWORD","name":"onboarding-config"}}}],"image":"acronboarding.azurecr.io/onboarding:latest","name":"onboarding","ports":[{"containerPort":3001}]}]}}}}
  creationTimestamp: "2021-09-08T08:13:30Z"
  generation: 1
  labels:
    name: onboarding
  name: onboarding
  namespace: mike
  resourceVersion: "720846"
  uid: 0812ecd4-9f73-435c-b1df-22ab4102d770
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: onboarding
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: onboarding
    spec:
      containers:
      - env:
        - name: IS_DOCKER
          value: "true"
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: PORT
              name: onboarding-config
        - name: DB_DIALECT
          valueFrom:
            secretKeyRef:
              key: DB_DIALECT
              name: onboarding-config
        - name: DB
          valueFrom:
            secretKeyRef:
              key: DB
              name: onboarding-config
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: onboarding-config
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: DB_PORT
              name: onboarding-config
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USERNAME
              name: onboarding-config
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: onboarding-config
        - name: APP_SETTINGS_FILE_PATH
          valueFrom:
            secretKeyRef:
              key: APP_SETTINGS_FILE_PATH
              name: onboarding-config
        - name: APM_URL
          valueFrom:
            secretKeyRef:
              key: APM_URL
              name: onboarding-config
        - name: KAFKA_HOST
          valueFrom:
            secretKeyRef:
              key: KAFKA_HOST
              name: onboarding-config
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: SECRET
              name: onboarding-config
        - name: EXPIRE_TOKEN
          valueFrom:
            secretKeyRef:
              key: EXPIRE_TOKEN
              name: onboarding-config
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              key: REDIS_PORT
              name: onboarding-config
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: REDIS_HOST
              name: onboarding-config
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: onboarding-config
        image: acronboarding.azurecr.io/onboarding:latest
        imagePullPolicy: Always
        name: onboarding
        ports:
        - containerPort: 3001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-09-08T08:13:31Z"
    lastUpdateTime: "2021-09-08T08:13:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-09-08T08:13:30Z"
    lastUpdateTime: "2021-09-08T08:13:31Z"
    message: ReplicaSet "onboarding-65849986b8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
